name: testing

on:
  push:
    branches: [ master ]

jobs:
  test-on-linux:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: set up conda environment
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: mol-env
          environment-file: environment.yml
          python-version: 3.7
          condarc-file: environment.yml
          auto-activate-base: false

      - name: check environment
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: test with pytest
        shell: bash -l {0}
        run: |
          pytest --cov=src --cov-report=xml
